<?php

namespace Tests\Unit;

use App\Transformers\Twitch\RawCommandTransformer;
use Tests\TestCase;

class RawCommandTransformerTest extends TestCase
{
    private RawCommandTransformer $transformer;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->transformer = new RawCommandTransformer();
    }


    /**
     * @dataProvider dataProvider
     */
    public function testCanTransform(string $payload, array $expected)
    {
        dump($this->transformer->transform($payload));
    }

    public static function dataProvider(): array
    {
        return [
            'scenario 1' =>  [
                'payload' => '@badge-info=subscriber/57;badges=broadcaster/1,subscriber/3036,partner/1;client-nonce=0808c18f77779ba81b0f4779757f9f6a;color=#8A2BE2;display-name=danielhe4rt;emotes=;first-msg=0;flags=;id=838b3201-7b65-4f8f-b96f-e20279c41fcc;mod=0;returning-chatter=0;room-id=227168488;subscriber=1;tmi-sent-ts=1684881587312;turbo=0;user-id=227168488;user-type= :danielhe4rt!danielhe4rt@danielhe4rt.tmi.twitch.tv PRIVMSG #danielhe4rt :a\r\n',
                'expected' => []
            ]
        ];
    }
}
